list: $/diveramkt/landingpage/models/ebook/columns.yaml
modelClass: Diveramkt\LandingPage\Models\Ebook
title: Ebooks
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/landingpage/ebooks/update/:id'
