name: CoursesNaMidia
form: $/diveramkt/landingpage/models/coursenamidia/fields.yaml
modelClass: Diveramkt\LandingPage\Models\CourseNaMidia
defaultRedirect: diveramkt/landingpage/coursesnamidia
create:
    redirect: 'diveramkt/landingpage/coursesnamidia/update/:id'
    redirectClose: diveramkt/landingpage/coursesnamidia
update:
    redirect: diveramkt/landingpage/coursesnamidia
    redirectClose: diveramkt/landingpage/coursesnamidia
