list: $/diveramkt/landingpage/models/coursefaq/columns.yaml
modelClass: Diveramkt\LandingPage\Models\CourseFAQ
title: CourseFAQs
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/landingpage/coursefaqs/update/:id'
