name: EventLectures
form: $/diveramkt/landingpage/models/eventlecture/fields.yaml
modelClass: Diveramkt\LandingPage\Models\EventLecture
defaultRedirect: diveramkt/landingpage/eventlectures
create:
    redirect: 'diveramkt/landingpage/eventlectures/update/:id'
    redirectClose: diveramkt/landingpage/eventlectures
update:
    redirect: diveramkt/landingpage/eventlectures
    redirectClose: diveramkt/landingpage/eventlectures
