list: $/diveramkt/landingpage/models/eventlecture/columns.yaml
modelClass: Diveramkt\LandingPage\Models\EventLecture
title: EventLectures
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/landingpage/eventlectures/update/:id'
