list: $/diveramkt/landingpage/models/extrapagescontent/columns.yaml
modelClass: Diveramkt\LandingPage\Models\ExtraPagesContent
title: ExtraPagesContents
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/landingpage/extrapagescontents/update/:id'
