list: $/diveramkt/landingpage/models/course/columns.yaml
modelClass: Diveramkt\LandingPage\Models\Course
title: Courses
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/landingpage/courses/update/:id'
