list: $/diveramkt/landingpage/models/extrapage/columns.yaml
modelClass: Diveramkt\LandingPage\Models\ExtraPage
title: ExtraPages
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/landingpage/extrapages/update/:id'
