name: ExtraPages
form: $/diveramkt/landingpage/models/extrapage/fields.yaml
modelClass: Diveramkt\LandingPage\Models\ExtraPage
defaultRedirect: diveramkt/landingpage/extrapages
create:
    redirect: 'diveramkt/landingpage/extrapages/update/:id'
    redirectClose: diveramkt/landingpage/extrapages
update:
    redirect: diveramkt/landingpage/extrapages
    redirectClose: diveramkt/landingpage/extrapages
