list: $/diveramkt/landingpage/models/coursetestmonial/columns.yaml
modelClass: Diveramkt\LandingPage\Models\CourseTestmonial
title: CourseTestmonials
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/landingpage/coursetestmonials/update/:id'
